kind = "web"
previewPath = "/"
title = "mzt"
version = "1.0.0"
id = "artifacts/mzt"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19721

[services.development]
run = "pnpm --filter @workspace/mzt run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mzt", "run", "build" ]
serve = "static"
publicDir = "artifacts/mzt/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19721"
BASE_PATH = "/"
