uploads = []
generated = []

[[outputs]]
id = "o49G4tYHrAXeDE199VU8q"
uri = "file://screenshots/putzermann-noir.jpg"
type = "image"
title = "putzermann core — noir theme"

[[outputs]]
id = "7sjZzTHta70doVz4XzC06"
uri = "file://screenshots/pysy-unchanged.jpg"
type = "image"
title = "pysy.exe — без изменений"

[[outputs]]
id = "F4HquZAmASDVjlErnpX7Y"
uri = "file://screenshots/putzermann-noir-final.jpg"
type = "image"
title = "putzermann core — финальный noir"

[[outputs]]
id = "3a596EzugpU0gs_ULS2CI"
uri = "file://screenshots/putzermann-pixel-noir.jpg"
type = "image"
title = "putzermann core — pixel-noir"

[[outputs]]
id = "tlW9GEEsG7q2sMNIHL6QB"
uri = "file://screenshots/putzermann-no-x.jpg"
type = "image"
title = "putzermann core — без лишних крестиков"

[[outputs]]
id = "Lob1As6BhdNVwmq9KQ1WA"
uri = "file://screenshots/pysy-no-x.jpg"
type = "image"
title = "pysy.exe — без лишних крестиков"

[[outputs]]
id = "qXIy4QQJNnlZpe5NarnNt"
uri = "file://screenshots/releases-secret-photo.jpg"
type = "image"
title = "стандартная тема — секретное фото"
